### ISSUE TITLE
Fix the tests

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/mirrors-countme#2]
# Story

As a contributor to mirrors-countme,
I want that I can run meaningful automatic tests,
so I can be confident that my contributions don’t break anything.

# Acceptance Criteria

- [x] All existing tests are performed successfully without large test data files in the repository.
  - [x] Running `pytest -v` locally works
  - [x] Running `tox` locally works
- [x] Tests cover all code which can be reasonably tested.
- [x] Code which can’t be tested without a putting up a huge effort (say handling of very rare, hard to mock errors) is commented and marked accordingly.

# Coordination

(Sub-)packages, modules that aren’t yet covered at all by tests (most important: \*):

- [x] `mirrors_countme/matchers.py` (\*, Nils, #63)
- [x] `mirrors_countme/output_items.py` (Nils, #76)
- [x] `mirrors_countme/progress.py` (Nils, #78)
- [x] `mirrors_countme/readers.py` (\*, Lenka, #71)
- [x] `mirrors_countme/scripts/countme_delete_totals.py` (Pedro, #72)
- [x] `mirrors_countme/scripts/countme_parse_access_log.py` (\*, Nils, #64)
- [x] `mirrors_countme/scripts/countme_totals.py` (\*, Pedro, #65)
- [x] `mirrors_countme/scripts/countme_trim_raw.py` (Nils, #75)
- [x] `mirrors_countme/writers.py` (\*, Nils, #66)

**Comment by LenkaSeg** [comment]
1.  `poetry run pytest -v` works and all tests pass (without large test data files)
2.  `tox` works

**Comment by nphilipp** [comment]
We put this back for the moment and tackle simplifying the code base (especially removing unused code) first.

**Comment by nphilipp** [comment]
⇒ #47

**Comment by nphilipp** [comment]
Whoops that got closed prematurely.

**Comment by LenkaSeg** [comment]
Yup, I think there's more to do for coverage :)
